// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzZ0R02xfu-tTXZC25A-C8x8XZH5kLjLk',
    appId: '1:775183300534:web:81090ba5f76df4b3d1b317',
    messagingSenderId: '775183300534',
    projectId: 'ui-clone-6b9f8',
    authDomain: 'ui-clone-6b9f8.firebaseapp.com',
    storageBucket: 'ui-clone-6b9f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAQmXI8MDf3buN6Mp0gQrmrYw_5mp9BTI',
    appId: '1:775183300534:android:32236a1c33255780d1b317',
    messagingSenderId: '775183300534',
    projectId: 'ui-clone-6b9f8',
    storageBucket: 'ui-clone-6b9f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIgT7nUXgOPKOgLQ3a57fGIyDeqnX1Gt4',
    appId: '1:775183300534:ios:f6efde20836ab279d1b317',
    messagingSenderId: '775183300534',
    projectId: 'ui-clone-6b9f8',
    storageBucket: 'ui-clone-6b9f8.appspot.com',
    iosClientId: '775183300534-fl4vkpp28pp4f4i5eqvh8594gj6omcqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIgT7nUXgOPKOgLQ3a57fGIyDeqnX1Gt4',
    appId: '1:775183300534:ios:f6efde20836ab279d1b317',
    messagingSenderId: '775183300534',
    projectId: 'ui-clone-6b9f8',
    storageBucket: 'ui-clone-6b9f8.appspot.com',
    iosClientId: '775183300534-fl4vkpp28pp4f4i5eqvh8594gj6omcqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentApp',
  );
}
